function(target_setup_sdl3_for_stylizer TGT)
	target_link_libraries(${TGT} PUBLIC SDL3::SDL3)

	if (APPLE)
		target_compile_options(${TGT} PRIVATE -x objective-c)
		target_link_libraries(${TGT} PRIVATE "-framework CoreVideo" "-framework IOKit" "-framework QuartzCore")

		if (IOS)
			target_link_libraries(${TGT} PRIVATE "-framework UIKit")
		else()
			target_link_libraries(${TGT} PRIVATE "-framework Cocoa")
		endif()
	endif()

	if(${SDL_VIDEO_DRIVER_COCOA})
		target_compile_definitions(${TGT} PUBLIC STYLIZER_API_SURFACE_SUPPORT_COCOA)
	endif()
	if(${SDL_VIDEO_DRIVER_WINDOWS})
		target_compile_definitions(${TGT} PUBLIC STYLIZER_API_SURFACE_SUPPORT_WIN32)
	endif()
	if(${SDL_X11})
		target_compile_definitions(${TGT} PUBLIC STYLIZER_API_SURFACE_SUPPORT_X11)
	endif()
	if(${SDL_WAYLAND})
		target_compile_definitions(${TGT} PUBLIC STYLIZER_API_SURFACE_SUPPORT_WAYLAND)
	endif()
endfunction(target_setup_glfw_for_stylizer)